<?php
/**
 * SignedUpload
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Autodesk\Forge\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Forge SDK
 *
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Autodesk\Forge\Client\Model;

use \ArrayAccess;

/**
 * SignedUpload Class Doc Comment
 *
 * @category    Class
 * @description Object json response
 * @package     Autodesk\Forge\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SignedUpload implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     * @var string
     */
    protected static $swaggerModelName = 'signedUpload';

    /**
     * Array of property to type mappings. Used for (de)serialization
     * @var string[]
     */
    protected static $swaggerTypes = [
        'upload_key' => 'string',
        'upload_expiration' => 'string',
        'url_expiration' => 'string',
        'urls' => 'string[]',
    ];

    /**
     * @return \string[]
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'upload_key' => 'uploadKey',
        'upload_expiration' => 'uploadExpiration',
        'url_expiration' => 'urlExpiration',
        'urls' => 'urls',
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'upload_key' => 'setUploadKey',
        'upload_expiration' => 'setUploadExpiration',
        'url_expiration' => 'setUrlExpiration',
        'urls' => 'setUrls',
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'upload_key' => 'getUploadKey',
        'upload_expiration' => 'getUploadExpiration',
        'url_expiration' => 'getUrlExpiration',
        'urls' => 'getUrls',
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['upload_key'] = isset($data['upload_key']) ? $data['upload_key'] : null;
        $this->container['upload_expiration'] = isset($data['upload_expiration']) ? $data['upload_expiration'] : null;
        $this->container['url_expiration'] = isset($data['url_expiration']) ? $data['url_expiration'] : null;
        $this->container['urls'] = isset($data['urls']) ? $data['urls'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }

    /**
     * Gets upload_key
     * @return string
     */
    public function getUploadKey()
    {
        return $this->container['upload_key'];
    }

    /**
     * Sets upload_key
     * @param string $upload_key Upload key
     * @return $this
     */
    public function setUploadKey($upload_key)
    {
        $this->container['upload_key'] = $upload_key;

        return $this;
    }

    /**
     * Gets upload_expiration
     * @return string
     */
    public function getUploadExpiration()
    {
        return $this->container['upload_expiration'];
    }

    /**
     * Sets upload_expiration
     * @param string $upload_expiration Upload expiration
     * @return $this
     */
    public function setUploadExpiration($upload_expiration)
    {
        $this->container['upload_expiration'] = $upload_expiration;

        return $this;
    }

    /**
     * Gets url_expiration
     * @return string
     */
    public function getUrlExpiration()
    {
        return $this->container['url_expiration'];
    }

    /**
     * Sets url_expiration
     * @param string $url_expiration Url expiration
     * @return $this
     */
    public function setUrlExpiration($url_expiration)
    {
        $this->container['url_expiration'] = $url_expiration;

        return $this;
    }

    /**
     * Gets urls
     * @return string[]
     */
    public function getUrls()
    {
        return $this->container['urls'];
    }

    /**
     * Sets urls
     * @param string[] $urls Object urls
     * @return $this
     */
    public function setUrls($urls)
    {
        $this->container['urls'] = $urls;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Autodesk\Forge\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Autodesk\Forge\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}